[uwsgi]
plugins=python3
protocol=uwsgi
log-format = [uWSGI] [pid: %(pid)|app: -|req: -/-] %(addr) (%(user)) {%(vars) vars in %(pktsize) bytes} [%(ctime)] %(method) %(uri) => generated %(rsize) bytes in %(msecs) msecs (%(proto) %(status)) %(headers)  headers in %(hsize) bytes (%(switches) switches on core %(core))

# Django's wsgi file
module = pp_application.wsgi

# 1 master process spawning max of <processes>
# worker for processing requests from client
master = true

# maximum number of worker processes
processes = 1

# the socket (use the full path to be safe)
socket = /app/config/pp.sock

# ... with appropriate permissions - may be needed
chmod-socket = 666

# clear environment on exit
vacuum = true

# !!! worker processes keep the memory, the recycling is necessary
# recycle worker processes each X requests
max-requests = 50

# allow large request bodies (because corp-wide cookies)
buffer-size = 32768

# limit memory usage to X MB
# reloads uwsgi process if its memory usage is higher
# !!!after!!! the request is processed in such process
reload-on-rss = 100

# ########################################### #
# DO NOT USE 'harakiri' OPTION                #
# (respawning if request takes more than X s) #
# it might kill sending data back for query   #
# #############################################
