user root;
events {
  worker_connections 768;
}
http {
  # octet, txt, csv, etc. formats
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  # Logging Settings
  access_log /dev/stdout;
  error_log /dev/stdout;

  # Gzip Settings
  gzip on;
  gzip_disable "msie6";
  server {
    listen 8000;
    server_name
       localhost local.att.com
       one.az.3pc.att.com
       selfservice.dev.att.com www.selfservice.dev.att.com
       selfservice.web.att.com www.selfservice.web.att.com
       one-creator-nprd.com-att-one.svc.cluster.local
       one-creator-prod.com-att-one.svc.cluster.local;

    location / {
      root /usr/share/nginx/html/one;
      index  index.html;
      try_files $uri $uri/ /index.html;
   }
  }
}
