apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-oidc-client-id #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-oidc-client-id # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-oidc-client-secret #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-oidc-client-secret # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-oidc-user-info #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-oidc-user-info # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-oidc-token #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-oidc-token # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-oidc-redirect-uri #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-oidc-redirect-uri # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-oidc-redirect-oidc #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-oidc-redirect-oidc # name of the akv object as in KV
      type: secret # akv object type