apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: ms-aad-oauth-tenant-id #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: ms-aad-oauth-tenant-id # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: ms-aad-oauth-client-id #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: ms-aad-oauth-client-id # name of the akv object as in KV
      type: secret # akv object type
---