apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-gps-host #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-gps-host # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-gps-port #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-gps-port # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-gps-user #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-gps-user # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-gps-password #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-gps-password # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-gps-sid #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-gps-sid # name of the akv object as in KV
      type: secret # akv object type