apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-django-secret-key #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-django-secret-key # name of the akv object as in KV
      type: secret # akv object type
---
