apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-action-gpsid #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-action-gpsid # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-action-user #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-action-user # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-action-password #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-action-password # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-action-url #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-action-url # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-action-mysql-host #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-action-mysql-host # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: one-action-mysql-port #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-action-mysql-port # name of the akv object as in KV
      type: secret # akv object type