# Generated by Django 3.2.2 on 2021-06-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(
                    db_column='ID', primary_key=True, serialize=False
                )),
                ('name', models.CharField(
                    blank=True, db_column='NAME', max_length=150, null=True
                )),
                ('attuid', models.CharField(
                    blank=True, db_column='ATTUID', max_length=6, null=True
                )),
                ('bc_user_id', models.CharField(
                    blank=True, db_column='BC_USER_ID',
                    max_length=150, null=True
                )),
            ],
            options={
                'db_table': 'css_users',
                'managed': False
            },
        ),
    ]
