# Generated by Django 3.2.2 on 2021-06-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessResult',
            fields=[
                ('id', models.AutoField(
                    db_column='ID', primary_key=True, serialize=False
                )),
                ('mongo_id', models.TextField(
                    db_column='MONGO_ID', blank=True, null=True
                )),
                ('result', models.TextField(db_column='RESULT')),
                ('status', models.CharField(
                    db_column='STATUS', max_length=120
                )),
                ('code', models.CharField(db_column='CODE', max_length=120)),
                ('result_type', models.CharField(
                    db_column='RESULT_TYPE', max_length=120
                )),
                ('special_return_type', models.TextField(
                    blank=True, db_column='SPECIAL_RETURN_TYPE', null=True
                )),
                ('special_result', models.TextField(
                    blank=True, db_column='SPECIAL_RESULT', null=True
                )),
                ('createdat', models.DateTimeField(
                    auto_now_add=True, db_column='createdAt'
                )),
                ('updatedat', models.DateTimeField(
                    auto_now=True, db_column='updatedAt'
                )),
                ('user', models.ForeignKey(
                    blank=True, db_column='USER_ID', null=True,
                    on_delete=django.db.models.deletion.CASCADE, to='orm.users'
                )),
            ],
            options={
                'db_table': 'css_process_result',
                'managed': True,
            },
        ),
    ]
