# Generated by Django 3.2.2 on 2021-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20210609_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processresult',
            name='code',
            field=models.CharField(blank=True, db_column='CODE', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='processresult',
            name='result',
            field=models.TextField(blank=True, db_column='RESULT', null=True),
        ),
        migrations.AlterField(
            model_name='processresult',
            name='result_type',
            field=models.CharField(blank=True, db_column='RESULT_TYPE', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='processresult',
            name='status',
            field=models.CharField(blank=True, db_column='STATUS', max_length=120, null=True),
        ),
    ]
