# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-06 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200608_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('templatebody', models.TextField()),
                ('generatedconfig', models.TextField()),
                ('dateCreated', models.DateTimeField(editable=False)),
                ('inputdata', models.TextField()),
                ('templateid', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='api.Template')),
            ],
        ),
    ]
