user root;
events {
  worker_connections 768;
}
http {
  # octet, txt, csv, etc. formats
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  log_format main '$http_x_forwarded_for - $remote_user [$time_local] "$host" "$request" '
            '$status $body_bytes_sent "$http_referer" '
            '"$http_user_agent" $request_time';

  # Logging Settings
  access_log /dev/stdout;
  error_log /dev/stdout;

  # Gzip Settings
  gzip on;
  gzip_disable "msie6";
  server {
    listen 8000;
    server_name
       localhost local.att.com
       selfservice.dev.att.com www.selfservice.dev.att.com
       selfservice.web.att.com www.selfservice.web.att.com
       onetouch-frontend-nprd.com-att-one.svc.cluster.local
       onetouch-frontend-prod.com-att-one.svc.cluster.local;

    root /usr/share/nginx/html/onetouch;
    index  index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
