# Project identification
sonar.projectKey=ATT-DP1_apm0013173-onetouch-frontend_4f49b492-3892-4ed7-bc85-1e2ed5d7901d

# Source code location
sonar.sources=.

# Custom properties
sonar.att.motsid=29786
sonar.att.view.type=prod

# SonarQube server details
sonar.host.url=https://sonar.it.att.com

# Exclusions
sonar.exclusions=chart/**, node_modules/**, dist/**, *.test.js

# Branch configuration
sonar.branch.name=azure/dev

# Code coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.test.inclusions=**/*.test.js

# Encoding
sonar.sourceEncoding=UTF-8