"""
Django settings for pp_application project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
import pymysql
from os import environ
from os.path import abspath, dirname, join, exists
from traceback import print_exc, format_exc

from django.db.backends.signals import connection_created
from django.dispatch import receiver


pymysql.version_info = (1, 4, 2, "final", 0)
pymysql.install_as_MySQLdb()
BASE_DIR = dirname(dirname(abspath(__file__)))
ENV = environ.get("ENV", "dev").lower()

ON_AZURE = True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ.get("DJANGO_SECRET_KEY", "fallback-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "local.att.com",
    "selfservice.dev.att.com",
    "selfservice.web.att.com",
    "paperplane.dev.att.com",
    "paperplane.web.att.com",
    "paperplane.it.att.com",
    "paperplane-nprd.com-att-one.svc.cluster.local",
    "paperplane-prod.com-att-one.svc.cluster.local"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'pp_application',
    'api',
    'broker'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'pp_application.settings.exc_handler'
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'pp_application.middleware.auth.XAuthorization',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if ON_AZURE and environ.get("AAF_MIDDLEWARE"):
    MW_INJECT = MIDDLEWARE.index("pp_application.middleware.auth.XAuthorization")
    MIDDLEWARE = MIDDLEWARE[:MW_INJECT] + [
        "pp_application.middleware.auth.AAFAuthorization"
    ] + MIDDLEWARE[MW_INJECT:]

ROOT_URLCONF = 'pp_application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pp_application.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.mysql",
        "NAME": environ.get("PP_NAME", "paperplane"),
        "USER": environ.get("PP_USER", "root"),
        "PASSWORD": environ.get("PP_PASSWORD", "paperplane"),
        "HOST": environ.get("PP_HOST", "172.17.0.1"),
        "PORT": int(environ.get("PP_PORT", 42424)),
        "AUTOCOMMIT": True
    }
}

# Azure MySQL DB server requires TLS. Use the BaltimoreCyberTrustRoot CA certificate
# Download from: https://dl.cacerts.digicert.com/BaltimoreCyberTrustRoot.crt.pem
# Docs: https://learn.microsoft.com/en-us/azure/mysql/single-server/concepts-ssl-connection-security
if ON_AZURE:
    print("Adjusting DB settings with TLS for Azure")
    CA_CERT_PATH = "/etc/ssl/certs/ca-certificates.crt"
    DATABASES["default"]["OPTIONS"] = {
        "ssl": {
            "ca": CA_CERT_PATH
        }
    }
    print(f'Options: {DATABASES["default"]["OPTIONS"]}')

if "test" in sys.argv or ENV == "unittest":
    DATABASES = {"default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "paperplane",
        "AUTOCOMMIT": True
    }}

LOGGING = {
    'version': 1,
    'formatters': {
        'verbose': {
            'format': (
                "[Django] {levelname} {asctime} {module}"
                " {process:d} {thread:d} {message}"
            ),
            'style': '{',
        },
        'simple': {
            'format': '[Django] {levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': [],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        }
    },
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console'],
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [{
    "NAME": (
        "django.contrib.auth.password_validation"
        ".UserAttributeSimilarityValidator"
    )
}, {
    "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"
}, {
    "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"
}, {
    "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"
}]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

MYSQL_DUPLICATE_ENTRY = 1062
STATIC_URL = '/static/'
STATIC_ROOT = f'{os.environ["APP_DIR"]}/backend/api/static'
SMTP_URL = environ.get("SMTP_HOST", "smtp.it.att.com")
SMTP_PORT = int(environ.get("SMTP_PORT", "25"))
SMTP_USER = environ.get("SMTP_USER")
SMTP_PASSWORD = environ.get("SMTP_PASSWORD")
DEFAULT_FROM_EMAIL = "m16735-ap@mta01.att-mail.com"
PROXY = {
    "http": environ.get("ATT_PROXY"),
    "https": environ.get("ATT_PROXY")
}
if environ.get("IGNORE_ATT_PROXY"):
    PROXY = {}
WEBEX_API_URL = "https://api.ciscospark.com/v1"
WEBEX_ATT_ORG = "79333ba2-edda-402a-b9a3-a8b15f91389a"
MATOMO_URLS = {
    "dev": "http://tmatomo.test.att.com/matomo/matomo.php",
    "test": "http://tmatomo.test.att.com/matomo/matomo.php",
    "perf": "http://tmatomo.web.att.com/matomo/matomo.php",
    "prod": "http://tmatomo.web.att.com/matomo/matomo.php"
}
if ON_AZURE and not environ.get("PP_IGNORE_MATOMO_HTTPS"):
    MATOMO_URLS = {
        key: val.replace("http:", "https:")
        for key, val in MATOMO_URLS.items()
    }
MATOMO_IDS = {"dev": 106, "test": 106, "perf": 47, "prod": 47}
TMATOMO_API_TOKEN = environ.get("TMATOMO_API_TOKEN")
DOC_PATH = join(dirname(abspath(__file__)), "documents")


def exc_handler(exc, context):
    # Call REST framework's default exception handler first,
    # to get the standard error response.
    # pylint: disable=import-outside-toplevel
    from rest_framework.views import exception_handler
    response = exception_handler(exc, context)

    # Now add the HTTP status code to the response.
    if response is not None:
        response.data['status_code'] = response.status_code

    try:
        print("Sending crash email")
        # pylint: disable=import-outside-toplevel
        view = getattr(context.get("view", {}), "__dict__", {})
        headers = view.get("headers", {})
        detail = exc.detail
        req = context.get('request')
        headers = getattr(req, "headers", {})
        data = getattr(req, "data", {})
        url = getattr(req, "url", None)

        from broker.handlers import send_email
        print(send_email(
            subject=f"Paperplane {ENV} - Crash",
            from_email=DEFAULT_FROM_EMAIL,
            display_name=DEFAULT_FROM_EMAIL,
            to_emails=["ms639x@intl.att.com"],
            body=(
                f"Response: {response}\n"
                f"Detail: {detail}\n"
                f"Context: {context}\n"
                f"View: {context.get('view')}\n"
                f"Request: {req}\n"
                f"Path: {url}\n"
                f"Headers: {headers}\n"
                f"Data: {data}\n"
                f"\n Traceback: {format_exc()}"
            ),
            options={"skip_validation": True}
        ))
    except Exception:  # pylint: disable=broad-except
        print("Can't send crash email")
        print_exc()

    return response


def get_document(name):
    with open(join(DOC_PATH, name)) as file:
        return file.read()


@receiver(connection_created)
def connection_init(sender, connection, **__):
    # pylint: disable=unused-argument
    if "test" in sys.argv or ENV == "unittest":
        # Django migrations don't use correctly ALTER with libSQLite3.31+!!!
        connection.cursor().execute("PRAGMA legacy_alter_table = ON")
        return
    print("Setting autocommit on connection start")
    connection.cursor().execute("SET autocommit=1")
