/**
 * @param {import("sequelize").QueryInterface} queryInterface
 * @param {import("sequelize").DataTypes} Sequelize
 */

function up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert(
        'CSS_ROUTE_TO_ACTION', [{
            ID: 12,
            METHOD: 'POST',
            ROUTE: '/service/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        },{
            ID: 13,
            METHOD: 'PUT',
            ROUTE: '/service/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 14,
            METHOD: 'GET',
            ROUTE: '/service/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 15,
            METHOD: 'DELETE',
            ROUTE: '/permission/services/customer/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 16,
            METHOD: 'POST',
            ROUTE: '/permission/services/customer/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 17,
            METHOD: 'GET',
            ROUTE: '/permission/services/customer/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 18,
            METHOD: 'DELETE',
            ROUTE: '/permission/services/role/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 19,
            METHOD: 'POST',
            ROUTE: '/permission/services/role/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 20,
            METHOD: 'GET',
            ROUTE: '/permission/services/role/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 21,
            METHOD: 'DELETE',
            ROUTE: '/permission/services/user/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 22,
            METHOD: 'POST',
            ROUTE: '/permission/services/user/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 23,
            METHOD: 'GET',
            ROUTE: '/permission/services/user/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 24,
            METHOD: 'DELETE',
            ROUTE: '/permission/template/customer/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 25,
            METHOD: 'GET',
            ROUTE: '/permission/template/customer/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 26,
            METHOD: 'POST',
            ROUTE: '/permission/template/customer/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 27,
            METHOD: 'DELETE',
            ROUTE: '/permission/template/role/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 28,
            METHOD: 'GET',
            ROUTE: '/permission/template/role/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 29,
            METHOD: 'POST',
            ROUTE: '/permission/template/role/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 30,
            METHOD: 'DELETE',
            ROUTE: '/permission/template/user/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 31,
            METHOD: 'GET',
            ROUTE: '/permission/template/user/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 32,
            METHOD: 'POST',
            ROUTE: '/permission/template/user/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 33,
            METHOD: 'DELETE',
            ROUTE: '/permission/service/customer/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 34,
            METHOD: 'GET',
            ROUTE: '/permission/service/customer/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 35,
            METHOD: 'POST',
            ROUTE: '/permission/service/customer/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 36,
            METHOD: 'DELETE',
            ROUTE: '/permission/service/role/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 37,
            METHOD: 'GET',
            ROUTE: '/permission/service/role/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 38,
            METHOD: 'POST',
            ROUTE: '/permission/service/role/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 39,
            METHOD: 'GET',
            ROUTE: '/bc/users/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 40,
            METHOD: 'DELETE',
            ROUTE: '/permission/service/user/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 41,
            METHOD: 'GET',
            ROUTE: '/permission/service/user/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 42,
            METHOD: 'POST',
            ROUTE: '/permission/service/user/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 43,
            METHOD: 'GET',
            ROUTE: '/workflows/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 44,
            METHOD: 'GET',
            ROUTE: '/node-list/actions/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 45,
            METHOD: 'DELETE',
            ROUTE: '/customer/gps-data/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 46,
            METHOD: 'GET',
            ROUTE: '/customer/gps-data/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 47,
            METHOD: 'POST',
            ROUTE: '/customer/gps-data/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 48,
            METHOD: 'DELETE',
            ROUTE: '/service/customer/orchestrator-list/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 49,
            METHOD: 'GET',
            ROUTE: '/service/customer/orchestrator-list/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 50,
            METHOD: 'POST',
            ROUTE: '/service/customer/orchestrator-list/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 51,
            METHOD: 'GET',
            ROUTE: '/service/customer/mcap-credentials/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 52,
            METHOD: 'PUT',
            ROUTE: '/service/customer/mcap-credentials/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 53,
            METHOD: 'POST',
            ROUTE: '/service/customer/mcap-credentials/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 54,
            METHOD: 'DELETE',
            ROUTE: '/customer/service/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 55,
            METHOD: 'POST',
            ROUTE: '/customer/service/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 56,
            METHOD: 'GET',
            ROUTE: '/customer/service/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 57,
            METHOD: 'DELETE',
            ROUTE: '/service/customer/action-data/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 58,
            METHOD: 'POST',
            ROUTE: '/service/customer/action-data/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 59,
            METHOD: 'GET',
            ROUTE: '/service/customer/action-data/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 60,
            METHOD: 'PUT',
            ROUTE: '/customer/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 61,
            METHOD: 'POST',
            ROUTE: '/customer/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 62,
            METHOD: 'GET',
            ROUTE: '/customer/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 63,
            METHOD: 'PUT',
            ROUTE: '/roles/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 64,
            METHOD: 'GET',
            ROUTE: '/users/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 65,
            METHOD: 'GET',
            ROUTE: '/customers/status/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 66,
            METHOD: 'GET',
            ROUTE: '/customers/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 67,
            METHOD: 'GET',
            ROUTE: '/service/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 68,
            METHOD: 'GET',
            ROUTE: '/roles/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 69,
            METHOD: 'GET',
            ROUTE: '/workflow/action/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 70,
            METHOD: 'POST',
            ROUTE: '/action-template/cArche/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 71,
            METHOD: 'GET',
            ROUTE: '/action-template/cArche/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 72,
            METHOD: 'PUT',
            ROUTE: '/action-template/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 73,
            METHOD: 'POST',
            ROUTE: '/action-template/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 74,
            METHOD: 'DELETE',
            ROUTE: '/action-template/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 75,
            METHOD: 'GET',
            ROUTE: '/action-template/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 76,
            METHOD: 'GET',
            ROUTE: '/action-template/services/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 77,
            METHOD: 'GET',
            ROUTE: '/action-template/vendor-type/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 78,
            METHOD: 'GET',
            ROUTE: '/cArche/template/types/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 79,
            METHOD: 'GET',
            ROUTE: '/cArche/template/content-types/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 80,
            METHOD: 'POST',
            ROUTE: '/cArche/template/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 81,
            METHOD: 'PUT',
            ROUTE: '/cArche/template/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 82,
            METHOD: 'DELETE',
            ROUTE: '/cArche/template/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 83,
            METHOD: 'GET',
            ROUTE: '/cArche/template/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 84,
            METHOD: 'GET',
            ROUTE: '/cArche/template-list/contract-id/service/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 85,
            METHOD: 'GET',
            ROUTE: '/cArche/variables/template-id/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 86,
            METHOD: 'GET',
            ROUTE: '/cArche/variables/name/service/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }, {
            ID: 87,
            METHOD: 'GET',
            ROUTE: '/cArche/variables/name/contract-id/',
            ACTION_ID: null,
            SCHEDULER: false,
            TYPE: 'one'
        }
    ], {}
    );
}

/**
 * @param {import("sequelize").QueryInterface} queryInterface
 * @param {import("sequelize").DataTypes} Sequelize
 */
function down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete(
        'CSS_ROUTE_TO_ACTION', {
        ID: { [Sequelize.Op.in]: [12, 87] }
    }, {}
    );
}


module.exports = { up, down };
