# Production Environment values for css-data-aggregator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceName: css-data-aggregator
namespace: com-att-one
replicaCount: 1
keyVaultName: eastus2-one-prodkv

image:
  repository: oneeastus2cr2azn0hvf.azurecr.io/css-data-aggregator
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "prod-latest"
  containerPort: 8000
  env:
    - name: SECRET_KEY
      value: "aggregator-one-django-secret-key@azurekeyvault"
    - name: AAF_USERNAME
      value: "aggregator-one-aaf-username@azurekeyvault"
    - name: AAF_PASSWORD
      value: "aggregator-one-aaf-password@azurekeyvault"
    - name: CRYPT_AUTH_TOKEN
      value: "aggregator-one-camunda-crypt-token@azurekeyvault"
    - name: CRYPT_KDBX_VELOCLOUD_PASSWORD
      value: "aggregator-one-crypt-password@azurekeyvault"
    - name: CRYPT_KDBX_VMANAGE_PASSWORD
      value: "aggregator-one-crypt-password@azurekeyvault"
    

    - name: CRYPT_BASE_URL
      value: "http://crypt-prod.com-att-one.svc.cluster.local:8000/api"
    - name: CSS_ORM_URL
      value: "http://one-controller-prod-orm.com-att-one.svc.cluster.local:7000/api"
    - name: CSS_RA_VELOCLOUD_URL
      value: "http://css-ra-velocloud-prod.com-att-one.svc.cluster.local:8000/api"
    - name: CSS_RA_VMANAGE_URL
      value: "http://css-ra-vmanage-prod.com-att-one.svc.cluster.local:8000/api"
    - name: CSS_RA_UTILITIES_URL
      value: "http://css-ra-utilities-prod.com-att-one.svc.cluster.local:8000/api"

    - name: https_proxy
      value: "http://proxy.conexus.svc.local:3128"
    - name: http_proxy
      value: "http://proxy.conexus.svc.local:3128"
    - name: no_proxy
      value: ".extensions.svc,.vault.azure.net,localhost,127.0.0.1,10.0.16.0/24,.svc.cluster.local,.azurecr.io,.azure.com"

ingress:
  enabled: true
  className: ""
  annotations:
    linkerd.io/inject: enabled
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
  hosts:
    - host: selfservice.web.att.com
      paths:
        - path: /svc/aggregator(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: selfservice-web-tls-certificate
      hosts:
        - selfservice.web.att.com

volumeMounts:
  - mountPath: /app/aggregator/static
    name: aggregator-config
  - mountPath: /app/config
    name: aggregator-config
  - mountPath: /var/lib/nginx/logs
    name: nginx-config
  - mountPath: /var/lib/nginx/tmp
    name: nginx-config
  - mountPath: /tmp
    name: nginx-config

volumes:
  - name: aggregator-config
    emptyDir: {}
  - name: nginx-config
    emptyDir: {}

resources:
  limits:
    cpu: 1000m
    memory: 6Gi
  requests:
    cpu: 500m
    memory: 2Gi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75