apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: velocloud-django-secret #as in deployment yaml
  namespace: {{ .Values.namespace }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: velocloud-django-secret # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: velo-aaf-username #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-aaf-username # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: velo-aaf-password #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-aaf-password # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: velo-paperplane-token #as in deployment yaml
  namespace: {{ .Values.namespace }}
  {{- with .Values.akvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-paperplane-token # name of the akv object as in KV
      type: secret # akv object type