apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: carche-config-ini #as in deployment yaml
  namespace: {{ .Values.namespace }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: carche-config-ini # name of the akv object as in KV
      type: secret # akv object type