[uwsgi]
# Load the Python 3 plugin
plugins = python3

# Use the uWSGI protocol
protocol = uwsgi

# Define the log format
log-format = [uWSGI] [pid: %(pid)|app: -|req: -/-] %(addr) (%(user)) {%(vars) vars in %(pktsize) bytes} [%(ctime)] %(method) %(uri) => generated %(rsize) bytes in %(msecs) msecs (%(proto) %(status)) %(headers) headers in %(hsize) bytes (%(switches) switches on core %(core))

# Ensure this points to your WSGI application
module = aggregator.wsgi

# Enable master process
master = true

# Number of worker processes
processes = 2

# Path to the uWSGI socket file
socket = /app/config/aggregator.sock

# Set permissions for the socket file
chmod-socket = 666

# Clean up the environment when the server stops
vacuum = true

# Maximum number of requests a worker will process before being recycled
max-requests = 50

# Size of the internal buffer
buffer-size = 32768

# Reload workers when RSS memory exceeds 100MB
reload-on-rss = 100

# ########################################### #
# DO NOT USE 'harakiri' OPTION                #
# (respawning if request takes more than X s) #
# it might kill sending data back for query   #
# #############################################