apiVersion: configuration.lgw.att.com/v1
kind: LGWService
metadata:
  name: com-att-paperplane-dev-paperplanenew
  namespace: com-att-paperplane-dev
spec:
  grm_environment_context: DEV
  grm_route_offer: DEFAULT
  grm_service_name: com.att.paperplane.paperplanenew
  grm_service_version: '0'
  grm_subcontext: /
  hosts:
  - paperplane.dev.att.com
  https_only: true
  methods:
  - OPTIONS
  - GET
  - HEAD
  - POST
  - PUT
  - DELETE
  - TRACE
  - CONNECT
  - PATCH
  name: com-att-paperplane-dev-paperplanenew
  plugins:
  - config:
      aafenv: prod
      aaftype: com.att.paperplane.dev.access
      cspsysname: com-att-paperplane-dev
    enabled: true
    name: aaf_plugin
  - config:
      credentials: true
      exposed_headers: Authorization
      headers: Accept,Authorization,Accept-Version,Content-Length,Content-MD5,Content-Type,Date
      methods: HEAD,GET,POST,PUT,PATCH,DELETE
      origins: paperplane.dev.att.com
      preflight_continue: true
    enabled: true
    name: cors
  preserve_host: true
  strip_uri: true
  tenant_namespace: com.att.paperplane
  upstream_url: null
  uris:
  - /
