apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: crypt-django-secret #as in deployment yaml
  namespace: {{ .Values.namespace }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: crypt-django-secret # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: crypt-mysql-database #as in deployment yaml
  namespace: {{ .Values.namespace }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: crypt-mysql-database # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: crypt-mysql-user #as in deployment yaml
  namespace: {{ .Values.namespace }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: crypt-mysql-user # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: crypt-mysql-password #as in deployment yaml
  namespace: {{ .Values.namespace }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: crypt-mysql-password # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: crypt-mysql-host #as in deployment yaml
  namespace: {{ .Values.namespace }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-mysql-host # name of the akv object as in KV
      type: secret # akv object type
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: crypt-mysql-port #as in deployment yaml
  namespace: {{ .Values.namespace }}
spec:
  vault:
    name: {{ .Values.keyVaultName }} # name of key vault
    object:
      name: one-mysql-port # name of the akv object as in KV
      type: secret # akv object type
