"""
Django settings for carche_project project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import configparser
from datetime import date
from os.path import join, dirname, abspath
from os import environ
import socket


BASE_DIR = dirname(dirname(abspath(__file__)))
CONF_FILE = join(dirname(BASE_DIR), 'config', '.conf.ini')

# Reading credentials from configuration file
settings = configparser.ConfigParser()
settings.read(CONF_FILE)

hostname = socket.gethostname()


if 'CSS_ENV' in environ:
    ENV = environ.get("CSS_ENV")
    print("enviroment " + ENV)

if ENV != "local":
    print(ENV)

DB = 'MYSQL_DB'
SECRET_KEY = settings.get('DJANGO_APP', 'secret_key')

DB_NAME = settings.get(DB, 'db')
HOSTNAME = settings.get(DB, 'hostname')
PORT = settings.get(DB, 'port')
USER = settings.get(DB, 'user')
PASSWORD = settings.get(DB, 'password')
CERTS = "/usr/share/ca-certificates"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENV != "prod"

ALLOWED_HOSTS = [
    environ.get('POD_IP'),
    environ.get('HOST_IP'),
    "localhost",
    "local.att.com",
    "selfservice.dev.att.com",
    "selfservice.web.att.com",
    "one-controller-nprd-carche.com-att-one.cluster.local",
    "one-controller-prod-carche.com-att-one.cluster.local",
    "carche-nprd.com-att-one.svc.cluster.local",
    "carche-prod.com-att-one.svc.cluster.local"
]

CORS_ORIGIN_ALLOW_ALL = True
# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_tracking',
    'api',
    'utils',
    'corsheaders',
)

MIDDLEWARE = (
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'carche_project.middleware.auth.AAFAuthorization',
    'carche_project.middleware.auth.XAuthorization',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

ROOT_URLCONF = 'carche_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'carche_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_NAME,
        'USER': USER,
        'PASSWORD': PASSWORD,
        'HOST': HOSTNAME,
        'PORT': PORT,
        'OPTIONS': {
            'ssl': {
                'ca': "/etc/ssl/certs/ca-certificates.crt",
                'check_hostname': False,
                'verify_cert': False,
                'verify_identity': False
            },
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

APPEND_SLASH = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# STATIC_URL = '/static/'
FORCE_SCRIPT_NAME = environ.get("SCRIPT_NAME", "")
STATIC_URL = f'{FORCE_SCRIPT_NAME}/static/'
STATIC_ROOT = f'{environ["APP_DIR"]}/static'

MAX_LOG_SIZE = 1024 * 1024 * 5  # 5 MB
MAX_LOG_COUNT = 5
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s - %(levelname)s - %(message)s'
        },
        'simple': {
            'format': '%(levelname)s - %(message)s'
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'debug_file_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': join(
                # todo: this is baked, the date is set only once on import
                BASE_DIR, 'logs', f"{date.today()}-debug.log"
            ),
            'maxBytes': MAX_LOG_SIZE,
            'backupCount': MAX_LOG_COUNT,
            'formatter': 'verbose'
        },
        'error_file_handler': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': join(
                # todo: this is baked, the date is set only once on import
                BASE_DIR, 'logs', f"{date.today()}-error.log"
            ),
            'maxBytes': MAX_LOG_SIZE,
            'backupCount': MAX_LOG_COUNT,
            'formatter': 'verbose'
        },
        'django_error_file_handler': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': join(
                # todo: this is baked, the date is set only once on import
                BASE_DIR, 'logs', f"ldjango-{date.today()}-error.log"
            ),
            'maxBytes': MAX_LOG_SIZE,
            'backupCount': MAX_LOG_COUNT,
            'formatter': 'simple'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'django_error_file_handler'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django_app': {
            'handlers': [
                'console', 'debug_file_handler', 'error_file_handler'
            ],
            'level': 'DEBUG',
            'propagate': True,
        }
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ]
}
