{{- $names := list 
    "vmanage-django-secret"
}}
{{- range $names }}
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
    name: {{ . }} #as in deployment yaml
    namespace: {{ $.Values.namespace }}
    {{- with $.Values.akvAnnotations }}
    annotations:
        {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
    vault:
        name: {{ $.Values.keyVaultName }} # name of key vault
        object:
            name: {{ . }} # name of the akv object as in KV
            type: secret # akv object type
{{- end }}