# Generated by Django 2.2.4 on 2019-08-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('backup_email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'applications',
                'managed': True,
            },
        ),
    ]
