# Generated by Django 2.2.4 on 2019-08-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(
                    primary_key=True, serialize=False
                )),
                ('type', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('to', models.TextField()),
                ('sender', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('app', models.ForeignKey(
                    db_column='app_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='api.ApplicationModel'
                )),
            ],
        ),
    ]
