# Generated by Django 2.2.4 on 2019-08-21 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authtoken', '0002_auto_20160226_1747'),
        ('api', '0002_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='token',
            field=models.ForeignKey(
                db_column='token_id',
                on_delete=django.db.models.deletion.CASCADE,
                to='authtoken.Token'
            ),
            preserve_default=False,
        )
    ]
