# Generated by Django 2.2.4 on 2019-08-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_changes_in_appmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
