# Generated by Django 2.2.4 on 2019-08-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_changes_in_messagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='messagemodel',
            table='messages',
        ),
    ]
