# Generated by Django 2.2.4 on 2019-08-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_renames_in_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='processed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
