# Generated by Django 2.2.4 on 2019-08-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_changes_in_messagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
