# Generated by Django 2.2.4 on 2019-10-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_changes_in_messagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTypeModel',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField())
            ],
            options={
                'db_table': 'subscription_type',
                'managed': True
            }
        )
    ]
