# Generated by Django 2.2.4 on 2019-10-08 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_seed_subscriptiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberModel',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('app', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='api.ApplicationModel'
                )),
                ('type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='api.SubscriptionTypeModel'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'subscribers',
                'managed': True,
            },
        ),
    ]
