# Generated by Django 2.2.4 on 2019-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_subscribermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTypeModel',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'message_type',
                'managed': True,
            },
        ),
    ]
