# Generated by Django 2.2.4 on 2019-10-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_seed_messagetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='type',
            new_name='backup_type',
        ),
    ]
