# Generated by Django 2.2.4 on 2019-10-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191014_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='backup_type',
            new_name='type',
        ),
    ]
