# Generated by Django 2.2.4 on 2019-10-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191014_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='new_type',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE,
                to='api.MessageTypeModel'
            ),
        ),
    ]
