# Generated by Django 2.2.4 on 2019-10-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_purge_invalid_msgtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='type',
        ),
    ]
