# Generated by Django 2.2.4 on 2019-10-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_messagemodel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='new_type',
            new_name='type',
        ),
    ]
