# Generated by Django 2.2.4 on 2019-10-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191014_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttDomains',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'att_domains',
                'managed': True,
            },
        ),
    ]
