# Generated by Django 2.2.4 on 2019-10-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_attdomains'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttDomains',
            new_name='AttDomainsModel',
        ),
    ]
