# Generated by Django 2.2.4 on 2019-10-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_seed_webex_messagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='bcc',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='reply_to',
            field=models.TextField(default=''),
        ),
    ]
