# Generated by Django 2.2.4 on 2019-10-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_bcc_replyto_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
