# Generated by Django 2.2.7 on 2019-11-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_messagemodel_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentModel',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('name', models.TextField()),
                ('binary', models.BinaryField()),
            ],
            options={
                'db_table': 'attachments',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='attachments',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to='api.AttachmentModel'
            ),
        ),
    ]
