# Generated by Django 2.2.7 on 2019-11-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20191127_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='attachments',
        ),
    ]
