# Generated by Django 2.2.7 on 2019-11-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_messagemodel_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentmodel',
            name='message',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE,
                to='api.MessageModel'
            ),
            preserve_default=False,
        ),
    ]
