# Generated by Django 2.2.7 on 2019-11-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_attachmentmodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmodel',
            name='binary',
            field=models.TextField(),
        ),
    ]
