# Generated by Django 2.2.7 on 2019-11-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_seed_leportal_messagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetypemodel',
            name='handle',
            field=models.BooleanField(default=1),
        ),
    ]
