# Generated by Django 3.0.3 on 2020-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_seed_webex_room_messagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
