# Generated by Django 3.0.3 on 2020-02-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_messagemodel_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnhandledMessageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('to', models.TextField()),
                ('reply_to', models.TextField(default='')),
                ('bcc', models.TextField(default='[]')),
                ('subject', models.CharField(default='', max_length=100)),
                ('sender', models.CharField(max_length=255)),
                ('time', models.DateTimeField(null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'unhandled_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotTypeModel',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'bot_type',
                'managed': True,
            },
        ),
    ]
