# Generated by Django 3.0.3 on 2020-02-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_seed_bottype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAuthHeaderModel',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('header', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='api.BotTypeModel'
                )),
            ],
            options={
                'db_table': 'bot_auth_header',
                'managed': True,
            },
        ),
    ]
