# Generated by Django 3.0.3 on 2020-02-06 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0040_fix_attdomains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='app_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='attdomainsmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bottypemodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='messagetypemodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontypemodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='botauthheadermodel',
            unique_together={('type', 'header')},
        ),
        migrations.AlterUniqueTogether(
            name='subscribermodel',
            unique_together={('user', 'app', 'type')},
        ),
    ]
