# Generated by Django 3.0.3 on 2020-02-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20200206_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='from_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='reply_to_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
