# Generated by Django 3.0.3 on 2020-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_from_replyto_applicationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='notify_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='notify_read',
            field=models.BooleanField(default=False),
        ),
    ]
