# Generated by Django 3.0.5 on 2020-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_seed_calendar_messagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='event_begin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='event_end',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='event_timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
