# Generated by Django 3.0.5 on 2020-04-17 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_add_event_fields_messagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(
                    blank=True, max_length=128, null=True, unique=True
                )),
                ('event_name', models.CharField(
                    blank=True, max_length=100, null=True
                )),
                ('event_description', models.TextField(blank=True, null=True)),
                ('event_begin', models.TextField(blank=True, null=True)),
                ('event_end', models.TextField(blank=True, null=True)),
                ('event_timezone', models.CharField(
                    blank=True, max_length=50, null=True
                )),
                ('active', models.BooleanField(default=True)),
                ('app', models.ForeignKey(
                    db_column='app_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='api.ApplicationModel'
                )),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
    ]
