# Generated by Django 3.0.5 on 2020-04-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_eventmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
