# Generated by Django 3.0.5 on 2020-04-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_eventmodel_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeModel',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('name', models.CharField(max_length=50, unique=True)),
                ('handle', models.BooleanField(default=1)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'event_type',
                'managed': True,
            },
        ),
    ]
