# Generated by Django 3.0.5 on 2020-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_messagetype_calendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='event_begin',
            new_name='begin',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='event_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='event_timezone',
            new_name='timezone',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='event_id',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='event_begin',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='event_description',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='event_end',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='event_timezone',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='event_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
