# Generated by Django 3.0.5 on 2020-04-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_message_refactor_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='rescheduled',
            field=models.BooleanField(default=False),
        ),
    ]
