# Generated by Django 3.0.5 on 2020-04-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20200420_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='type',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE,
                to='api.EventTypeModel'
            ),
            preserve_default=False,
        ),
    ]
