# Generated by Django 3.0.5 on 2020-04-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_eventmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='begin',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='end',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='timezone',
            field=models.CharField(default='GMT+2', max_length=50),
            preserve_default=False,
        ),
    ]
